# -*- coding: utf-8 -*-
# @Author: Rafael Direito
# @Date:   2022-10-24 14:17:09
# @Last Modified by:   Rafael Direito
# @Last Modified time: 2022-11-02 12:53:43
version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: testkeycloakdb
      POSTGRES_USER: testkeycloakuser
      POSTGRES_PASSWORD: testkeycloakpassword
    restart:
      always

  keycloak:
    image: jboss/keycloak:18.0.2 
    container_name: keycloak
    command:
      - " -b 0.0.0.0 "
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: testkeycloakdb
      DB_USER: testkeycloakuser
      DB_SCHEMA: public
      DB_PASSWORD: testkeycloakpassword
      KEYCLOAK_USER: keycloakuser
      KEYCLOAK_PASSWORD: keycloakpassword
<<<<<<< HEAD
=======
      # Fixes token related issues
>>>>>>> 0b0eb50b73753582531bbfba486fb39def3db34f
      #KEYCLOAK_HOSTNAME: keycloak
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_LOGLEVEL: DEBUG
      MY_REALM_NAME: vpilot
      MY_REALM_CLIENT: vpilot-client
      MY_REALM_CLIENT_SECRET: dummy_client_secret
      MY_REALM_ADMIN_SECRET: dummy_admin_secret
      # MY_REALM_REDIRECT_URI: "\"<uri_1>\",\"<uri_2>\""
      MY_REALM_REDIRECT_URI: "\"http://localhost:8000/*\",\"http://localhost:8001/*\""
      # REALM_ROLES: <role_1_name>:<role_1_description>;<role_2_name>:<role_2_description>
      REALM_ROLES: VPilot-Admin:VPilot Admin;Testbed-Admin:VPilot Testbed Admin
      # REALM_USERS: <user_1_username>:<user_1_password>:<user_1_role_1>,<user_1_role_2>;<user_2_username>:<user_2_password>:<user_2_role_1>,<user_2_role_2>
      REALM_USERS: 5gasp-admin:5gasp-password:VPilot-Admin,Testbed-Admin;itav:itav-password:None

    ports:
      - '8085:8080'
    depends_on:
      - postgres
    restart:
      always
